### PR TITLE
Fix: compile item text (fixes #173)

### LINKED ISSUE #173: Item text doesn't compile a11y_alt_text helper
### Subject of the issue
The [a11y_alt_text](https://github.com/adaptlearning/adapt-contrib-core/commit/a92c7ffdb431bdf126e080c009b3b9c324642755) helper tag syntax is being displayed instead of compiling the on screen text and hidden screen reader text.

### Expected behaviour
Using the helper should produce display text with an alternative hidden screen reader version.

Similar issues were raised and resolved previously for other components. See [Hotgraphic](https://github.com/adaptlearning/adapt-contrib-hotgraphic/issues/273) for reference.

### PR DESCRIPTION
**Pull request by kirsty-hames**
Fixes https://github.com/adaptlearning/adapt-contrib-matching/issues/173

To support the use of [a11y_alt_text](https://github.com/adaptlearning/adapt-contrib-core/commit/a92c7ffdb431bdf126e080c009b3b9c324642755) helper tag.

## PR Test
Add `a11y_alt_text` helper to Matching item `text` e.g. `{{a11y_alt_text '$5bn' 'five billion dollars'}}`.

In your course, go to the Matching item and '$5bn' should be displayed.

Using the browser devtools, inspect '$5bn' and the helper should have split out the on screen text and a11y text e.g.
`<span aria-hidden="true">$5bn</span><span class="aria-label">five billion dollars</span>`

### CODE REVIEW

**Review by joe-allen-89 — COMMENTED** [review]
Looks good @kirsty-hames, should also add compile to matchingDropDown.jsx so we can use it in the drop down lists?

**Review by oliverfoster — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by kirsty-hames** [comment]
> Looks good @kirsty-hames, should also add compile to matchingDropDown.jsx so we can use it in the drop down lists?

Thanks for the suggestion @joe-allen-89. If I do the same for _matchingDropDown_, the `text` property is also used for the [`<li text="">`](https://github.com/adaptlearning/adapt-contrib-matching/blob/61fd9acaa933892b1e65c013e8eefee19b3ab9b8/templates/matchingDropDown.jsx#L222) attribute. 
I'm not actually sure what the `text` attribute is for but I imagine we only need the on screen text rendered here?

I've tried using `text={a11y.normalize(compile(text))}` but you get both the on screen and screen reader text. See screenshot below. Other than creating a new property to override the `text` attribute, any other ideas?

normalise_compile

**Comment by oliverfoster** [comment]
text={text}

v5.0.0 hbs
https://github.com/adaptlearning/adapt-contrib-matching/blob/e68559762ea2b5bcef1c2abf86bd4517df407f0d/js/dropdownOption.js#L42

It's just left over from old code. It should be safe to remove.

**Review by oliverfoster — APPROVED** [review]

File: templates/matchingDropDown.jsx [hunk 1]
```diff
@@ -219,13 +219,12 @@ export default function MatchingDropDown(props) {
...
             className="dropdown-item js-dropdown-list-item"
             role="option"
-            text={text}
             value={_index}
             aria-selected={_isHighlighted || null}
             selected={_isHighlighted || null}
             onClick={onOptionClicked}
           >
-            <div className="dropdown-item__inner js-dropdown-list-item-inner u-no-select" dangerouslySetInnerHTML={{ __html: displayText || text }}>
+            <div className="dropdown-item__inner js-dropdown-list-item-inner u-no-select" dangerouslySetInnerHTML={{ __html: displayText || compile(text) }}>
```
Comment (oliverfoster) [inline templates/matchingDropDown.jsx:227]: compile doesn't exist in this file as it wasn't imported
