### PR TITLE
Fix: a11y combobox attributes (fixes #147)

### LINKED ISSUE #147: Align with wcag spec
Recommendation https://www.w3.org/TR/wai-aria-practices-1.2/examples/combobox/combobox-select-only.html

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #147

### Fix
* Added role, aria-controls and relevant id

### CODE REVIEW

File: templates/matchingDropDown.jsx [hunk 1]
```diff
@@ -205,6 +207,7 @@ export default function MatchingDropDown(props) {
           left: buttonOffsetLeft,
           width: buttonWidth
         }}
+        id="${_id}-matching-item-${_itemIndex}__list"
```
Comment (kirsty-hames) [inline templates/matchingDropDown.jsx:210]: Same eslint error as above.

**Review by kirsty-hames — COMMENTED** [review]
Testing this with VoiceOver in Safari functions as expected however the reading of the button isn't. "_Misspelt_" is announced before reading the button context (see screenshot below). I can't see why the "_Select an option_" text is being cut off. I'll test this with NVDA to compare.
Screenshot 2024-11-11 at 12 51 09

**Comment by oliverfoster** [comment]
> Testing this with VoiceOver in Safari functions as expected however the reading of the button isn't. "_Misspelt_" is announced before reading the button context (see screenshot below). I can't see why the "_Select an option_" text is being cut off. I'll test this with NVDA to compare. Screenshot 2024-11-11 at 12 51 09

looking at the example, we maybe have too many aria-labelledbys, perhaps the one on the ul could be removed?

https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/#sc1_label

image

**Comment by kirsty-hames** [comment]
Hey @oliverfoster, I've made a couple of commits to align this with the WCAG example you shared. Overall this is reading much better.

We still have the [issue](https://github.com/adaptlearning/adapt-contrib-matching/pull/198#pullrequestreview-2427347796) mentioned above where VoiceOver in Safari reads _"Misspelt"_ and cuts off the label. I can only replicate this in Safari. VoiceOver in Chrome reads beautifully. NVDA in Chrome and Edge read nicely too.

I'm running Safari v18.0.1 - not sure if this is a Safari specific issue or limited to a particular version. I'll give this a test on iPhone Safari and I'll see if I can replicate the issue. I'll also test the master branch (as it may be an issue prior to this PR).

File: templates/matchingDropDown.jsx [hunk 2]
```diff
@@ -176,16 +176,19 @@ export default function MatchingDropDown(props) {
...
         aria-haspopup="listbox"
         aria-expanded={isOpen}
+        aria-controls={`${_id}-matching-item-${_itemIndex}__list`}
         onMouseDown={onStartInteraction}
         onTouchStart={onStartInteraction}
         onClick={onButtonClick}
         ref={button}
-        aria-labelledby={props.questionTitleId + ' ' + props.questionTextId}
+        aria-labelledby={props.questionTitleId}
+        aria-activedescendant={highlightedOption && `dropdown__item__${_id}__${_itemIndex}__${highlightedOption._index}`}
```
Comment (joe-allen-89) [inline templates/matchingDropDown.jsx:188]: Moving aria-activedescendant from the listbox to the combobox is causing some strange behaviour for keyboard navigation/screen readers. Currently if I open the matching item the list items either not being read out (firefox) or missed entirely (chrome), both tested with NVDA. Is moving aria-activedescendant necessary?

Comment (kirsty-hames) [reply templates/matchingDropDown.jsx:188]: > Is moving aria-activedescendant necessary?
>
I don't think so. If I revert `aria-activedescendant` back to listbox, this reads as expected for NVDA on Chrome, Edge and FF. No change to VoiceOver on Safari and Chrome either. I'll commit this back.

Comment (kirsty-hames) [reply templates/matchingDropDown.jsx]: This is ready to retest in [98b84d6](https://github.com/adaptlearning/adapt-contrib-matching/pull/198/commits/98b84d6a13c7cd7480479a41f45cc8e28cd0dad0) please @joe-allen-89.

**Review by kirsty-hames — APPROVED** [review]

**Comment by oliverfoster** [comment]
One second, just reading again.

**Comment by oliverfoster** [comment]
What happens when there is no `text`? The `questionTitleId` element would go missing and the `aria-labelledby` would have no meaning.

**Comment by kirsty-hames** [comment]
> What happens when there is no `text`? The `questionTitleId` element would go missing and the `aria-labelledby` would have no meaning.

Good point! In this instance, should it read the following:

- `ariaQuestion`
- if `ariaQuestion` isn't set, then `displayTitle` `body` `instruction` ?

**Comment by oliverfoster** [comment]
Sounds great, yes.

**Comment by kirsty-hames** [comment]
> > What happens when there is no `text`? The `questionTitleId` element would go missing and the `aria-labelledby` would have no meaning.
> 
> Good point! In this instance, should it read the following:
> 
> * `ariaQuestion`
> * if `ariaQuestion` isn't set, then `displayTitle` `body` `instruction` ?

I've implemented the above in commit [b77f232](https://github.com/adaptlearning/adapt-contrib-matching/pull/198/commits/b77f232e38d6df1857ebf2d468afe612e5d5af80). Note, due to `aria-labelledby` requiring an `id`, `ariaQuestion` is provided as an `aria-label` instead.

In the instance, `aria-labelledby` and `aria-label` both exist, for example both item `text` and `ariaQuestion` are set, `aria-labelledby` takes precedence.

File: templates/matching.jsx [hunk 3]
```diff
@@ -49,8 +49,8 @@ export default function Matching(props) {
           const activeOption = _options.find(option => (option._itemIndex === _index) && option._isActive);
           const displayItemAsCorrect = (!_isEnabled && _shouldShowMarking && (_isCorrectAnswerShown || activeOption?._shouldBeSelected));
           const questionTitleId = `${_id}-matching-item-${_index}__title`;
-          const questionTextId = `${_id}-matching-item-${_index}__text`;
           const hasMultipleCorrectAnswers = _correctAnswers.length > 1;
+          const ariaLabel = text ? questionTitleId : (ariaQuestion ? null : `${_id}-header`);
```
Comment (oliverfoster) [inline templates/matching.jsx:53]:
```suggestion
          const ariaLabelledBy = text ? questionTitleId : (ariaQuestion ? null : `${_id}-header`);
```
The variable name `ariaLabel` isn't correct here, it's the `aria-labelledby` id that you're passing through, so perhaps change to make easier to read?

File: templates/matchingDropDown.jsx [hunk 4]
```diff
@@ -205,13 +209,14 @@ export default function MatchingDropDown(props) {
           left: buttonOffsetLeft,
           width: buttonWidth
         }}
+        id={`${_id}-matching-item-${_itemIndex}__list`}
         role="listbox"
         tabIndex="-1"
         onBlur={onListBlur}
         ref={list}
         disabled={!_isEnabled}
+        aria-labelledby={props.questionTitleId}
```
Comment (oliverfoster) [inline templates/matchingDropDown.jsx:218]:
```suggestion
        aria-labelledby={props.ariaLabelledBy}
```
This one also needs updating?

File: templates/matching.jsx [hunk 5]
```diff
@@ -70,7 +70,7 @@ export default function Matching(props) {
 
               <div className="matching-item__select-container js-matching-item-select-container">
 
-                <templates.matchingDropDown {...props} _itemIndex={_index} questionTitleId={questionTitleId} questionTextId={questionTextId}/>
+                <templates.matchingDropDown {...props} _itemIndex={_index} questionTitleId={questionTitleId} ariaLabel={ariaLabel}/>
```
[the remark this answers is not in the document]
Comment (kirsty-hames) [reply templates/matching.jsx]: Apologies this was missed. Fixed in https://github.com/adaptlearning/adapt-contrib-matching/pull/198/commits/d7efd805b2d57a483fadea34120730371fe4043b

File: templates/matchingDropDown.jsx [hunk 6]
```diff
@@ -176,16 +177,19 @@ export default function MatchingDropDown(props) {
...
+        role="combobox"
         aria-haspopup="listbox"
         aria-expanded={isOpen}
+        aria-controls={`${_id}-matching-item-${_itemIndex}__list`}
         onMouseDown={onStartInteraction}
         onTouchStart={onStartInteraction}
         onClick={onButtonClick}
         ref={button}
-        aria-labelledby={props.questionTitleId + ' ' + props.questionTextId}
+        aria-labelledby={props.ariaLabel}
```
[the remark this answers is not in the document]
Comment (kirsty-hames) [reply templates/matchingDropDown.jsx]: Apologies this was missed. Fixed in https://github.com/adaptlearning/adapt-contrib-matching/commit/d7efd805b2d57a483fadea34120730371fe4043b

I've retested and the button reads as per the following:

- If `text`, this sets the `aria-labelledby`
- otherwise, if `ariaQuestion`, this sets the `aria-label`
- otherwise `displayTitle body instruction` sets the `aria-labelledby`
