### PR TITLE
issue/2515 React, _hasItemScoring, _allowOnlyUniqueAnswers

### LINKED ISSUE #137: Dropdown select fails on reset (when using tutor)
There appears to be a bug with matching when notifications are stacked up and then closed. This is currently not the behaviour of tutor, but for any extensions that expand on the Adapt.notify stack it may cause issues.

Replication of bug can be achieved by using the hack outlined below:
1. Make a change to tutor that forces multiple popups (i.e. add another `notify.create(this.notifyOptions);` below the original on line https://github.com/adaptlearning/adapt-contrib-tutor/blob/master/js/TutorNotify.js#L26, to force the same popup twice)
2. Create a course using matching and an assessment with this altered tutor
3. The first dropdown selection and submission gives assessment feedback and tutor feedback (if configured)
4. Reset the assessment
5. Dropdown options appear on click, but options do not disappear (on click/blur/escape etc)

On console debugging, I can see that the blur event is not been fired on the list items at all. Not sure why the page loses this.

Use `monitorEvents($('.js-dropdown-list')[0], "control")` in the console to confirm difference in before and after reset behaviour.

NB: Functionality is intact when tutor is removed

### LINKED ISSUE #142: Allow only unique answers
Original requirement: https://community.adaptlearning.org/mod/forum/discuss.php?d=4080#p15019

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes https://github.com/adaptlearning/adapt_framework/issues/2515
fixes #137 
fixes #142 

### Changed
* To jsx from handlebars

### Fixed
* Background click away from the button or list now causes a blur

### Added
* Partial scoring is now possible with `_hasItemScoring`
* Unique answers with `_allowOnlyUniqueAnswers`

### CODE REVIEW

File: js/MatchingView.js [hunk 1]
```diff
@@ -0,0 +1,24 @@
+// import Adapt from 'core/js/adapt';
```
Comment (eleanor-heath) [inline js/MatchingView.js:1]: can we remove this comment

**Review by eleanor-heath — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by chris-steele — APPROVED** [review]
