### PR TITLE
Fix: Add correct +/ incorrect aria labels to ticks and crosses (fixes #154)

### LINKED ISSUE #154: accessibility: Add correct +/ incorrect aria labels to ticks and crosses
### Subject of the issue/enhancement/features
Tick and cross icons do not contain aria labels.

Relates to https://github.com/adaptlearning/adapt_framework/issues/2241

### Your environment
* Framework 5.22.3

### Steps to reproduce

1. Complete a Matching component with a mix of correct and incorrect responses
2. Toggle between Show Correct Answer and Show My Answer

### Expected behaviour
The tick and cross icons should have aria labels indicating if they represent correct or incorrect.

### Actual behaviour
No aria labels

### PR DESCRIPTION
**Pull request by swashbuck**
Fixes #154 

### Fix
Adds aria-labels of Correct or Incorrect to the tick and cross icons

### Testing
1. Complete a Matching component with a mix of correct and incorrect responses
2. Toggle between Show Correct Answer and Show My Answer
3. With a screenreader, tab up to where each answer is shown and then to the tick/cross icon.

Relates to https://github.com/adaptlearning/adapt_framework/issues/2241

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

File: templates/matching.jsx [hunk 1]
```diff
@@ -1,7 +1,10 @@
+import Adapt from 'core/js/adapt';
 import React from 'react';
 import { templates, classes } from 'core/js/reactHelpers';
 
 export default function Matching(props) {
+  const ariaLabels = Adapt.course.get('_globals')._accessibility._ariaLabels;
```
Comment (oliverfoster) [inline templates/matching.jsx:6]: `_globals` should be in the props

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by oliverfoster — APPROVED** [review]

**Review by ethan-lp — APPROVED** [review]
